CREATE TABLE `Pedido` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`PEDIDO` INT(255) NOT NULL AUTO_INCREMENT,
	`CLIENTE` BINARY NOT NULL AUTO_INCREMENT,
	`PREÇO` BINARY NOT NULL AUTO_INCREMENT,
	`DATA` BINARY NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `Nota Fiscal` (
	`ID` BINARY NOT NULL AUTO_INCREMENT,
	`CELULAR` varchar(255) NOT NULL AUTO_INCREMENT,
	`COMPUTADOR` varchar(255) NOT NULL AUTO_INCREMENT,
	`RADIO` varchar(255) NOT NULL AUTO_INCREMENT,
	`MICRO-ONDAS` varchar(255) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`ID`)
);

ALTER TABLE `Nota Fiscal` ADD CONSTRAINT `Nota Fiscal_fk0` FOREIGN KEY (`CELULAR`) REFERENCES `Pedido`(`PEDIDO`);



